kind: Pod
apiVersion: v1
metadata:
  name: ultra-test
spec:
  containers:
  - name: ultra-test
    image: ubuntu
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "apt update;apt install -y fio;while true; do sleep 30; done;" ]
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: ultra-disk